html = ''
js = ''
css = ''


with open('HTML/main.html', 'r') as f:
    html = f.read()

with open('HTML/main.js', 'r') as f:
    js = f.read()


with open('HTML/main.css', 'r') as f:
    css = f.read()

with open('HTML.vala', 'w') as f:
    f.write('//Do Not Edit, Page is Generated by build_page.py\n')
    f.write('public class HTML : GLib.Object{ public string html = """\n')
    f.write(html.format(pagejs=js, pagecss=css))
    f.write('"""; }\n')

# with open('HTML.html', 'w') as f:
#     f.write('public class HTML : GLib.Object{ public string html = """\n')
#     f.write(html.format(pagejs=js, pagecss=css))
#     f.write('"""; }\n')







